# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pE-B7eW7jpR8X9kKKEAwdoC7UvrhmGmW
"""

MODEL_CHECKPOINT = "allenai/led-base-16384"

OUTPUT_DIR = "./checkpoints/led_finetuned_summarizer"
LOGGING_DIR = "./logs"

CSV_PATH = "data/data_summarization.csv"

SEED = 42

MAX_INPUT_LENGTH = 4096
MAX_TARGET_LENGTH = 500