defaults:
  premise_path: output/premise.json
  output_path: output/plan.json
  logging_level: info
  MODEL:
    engine: mistralai/Mistral-7B-Instruct-v0.3
    tensor_parallel_size: 1
    server_type: vllm
    host: http://localhost
    port: 9741
    prompt_format: openai-chat
    temperature: 0.5
    top_p: 0.9
    frequency_penalty: 0
    presence_penalty: 0
    PLAN:
      SETTING:
        max_tokens: 150
        stop: []
      ENTITY:
        max_attempts: 2
        min_entities: 1
        max_entities: 1
        NAME:
          max_tokens: 16
          stop: ["\n", ",", ":", "("]
        DESCRIPTION:
          max_tokens: 80
      OUTLINE:
        max_attempts: 2
        expansion_policy: breadth-first
        max_depth: 1
        context: ancestors-with-siblings-children
        min_children: 1
        preferred_max_children: 1
        max_children: 1
        EVENT_DEPTH_0:
          max_tokens: 120
        EVENT:
          frequency_penalty: 0.5
          max_tokens: 120
        SCENE:
          context: ancestors-with-siblings
          max_tokens: 80
        ENTITY_DEPTH_0:
          max_tokens: 80
        ENTITY:
          max_tokens: 80
